### ISSUE TITLE
Update to last angular 

### ISSUE THREAD

**Issue by BjornMelgaard** [dflourusso/ng-tiddle#2]

**Comment by dflourusso** [comment]
Thanks, let me some days, i do not have time today, but i will update.

**Comment by BjornMelgaard** [comment]
Ok, and I also have a question: does module implement registration?

**Comment by dflourusso** [comment]
1 - Angular version updated.
2 - Yes, i can implement the registration, but i do not have time for while. If you need it fast, send me a pull request please. Thanks.

**Comment by BjornMelgaard** [comment]
Thanks to you
